apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: mhegyi/vprofileapp:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - name: vproapp-port
          containerPort: 8080

      initContainers:
      - name: init-mysql
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup vprodb.default.svc.cluster.local; do echo waiting for mysql; sleep 2; done;']
      - name: init-memcached
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup vprocache01.default.svc.cluster.local; do echo waiting for memcached; sleep 2; done;']
